# Shared CLI tools and editor build/runtime dependencies. No desktop packages.
brew "git"
brew "neovim"
brew "tmux"
brew "stow"
brew "go"
brew "tree-sitter-cli"
brew "python@3.14"
brew "uv"
brew "openjdk"
brew "pnpm"
brew "eza"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "bat"
brew "fzf"
brew "ripgrep"
